""" version which can be consumed from within the module """
VERSION_STR = "0.0.85"
DESCRIPTION = "pycmdtools is set of useful command line tools written in python"
APP_NAME = "pycmdtools"
LOGGER_NAME = "pycmdtools"
